[package]
edition.workspace = true
name = "program-schedulecommit-security"
version.workspace = true

[dependencies]
borsh = { workspace = true }
ephemeral-rollups-sdk = { workspace = true }
program-schedulecommit = { workspace = true, features = ["no-entrypoint"] }
solana-program = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[features]
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
default = []
no-entrypoint = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
