[package]
name = "test-tools-core"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

# Test tools that don't depend on any magicblock crates and thus can be used
# by all of them

[dependencies]
env_logger = { workspace = true }
log = { workspace = true }
magicblock-accounts-db = { workspace = true }
