[accounts]
remote = { url = "https://rpc.ironforge.network/devnet?apiKey=01HBGMPGFMCPPFCXDZ43Y1K80K", ws_url = ["wss://devnet.helius-rpc.com/?api-key=1bf47fbb-a652-4e8d-b35a-c07af6f60391", "wss://magicblo-devd137-9da1.devnet.rpcpool.com/93b47c17-2067-4a37-9778-ed731f9c6427"]}
lifecycle = "ephemeral"
commit = { frequency_millis = 10_000 }

[accounts.db]
db-size = 2147483648 # 2 GB
block-size = "block256" # possible values block128 | block256 | block512
index-map-size = 67108864 # 64 MB
max-snapshots = 4
snapshot-frequency = 1024

[rpc]
addr = "0.0.0.0"
port = 8899

[validator]
millis_per_slot = 50