[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "magicblock-version"
repository.workspace = true
version.workspace = true

[dependencies]
git-version = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
solana-feature-set = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sanitize = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(RUSTC_WITHOUT_SPECIALIZATION)',
    'cfg(RUSTC_WITH_SPECIALIZATION)'
] }
