# Review behavior: one high-signal pass per PR, low chatter
reviews:
  profile: assertive

  high_level_summary: true
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false

  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  auto_apply_labels: false
  auto_assign_reviewers: false

  in_progress_fortune: false
  poem: false

  auto_review:
    auto_incremental_review: false
    drafts: false
    base_branches: [".*"]

# Disable conversational noise
chat:
  art: false
  auto_reply: false

# Knowledge base: stay strictly repo-local
knowledge_base:
  web_search:
    enabled: false

# Tooling: only what’s relevant for a Rust infra repo
tools:
  clippy:
    enabled: true
  shellcheck:
    enabled: true
  actionlint:
    enabled: true
  yamllint:
    enabled: true
  gitleaks:
    enabled: true
  osvScanner:
    enabled: true

  # Explicitly disable unrelated ecosystems / noisy analyzers
  biome:
    enabled: false
  eslint:
    enabled: false
  oxc:
    enabled: false
  semgrep:
    enabled: false
  languagetool:
    enabled: false
  markdownlint:
    enabled: false
  buf:
    enabled: false
  dotenvLint:
    enabled: false
  checkmake:
    enabled: false
  github-checks:
    enabled: false

# Code generation is allowed
code_generation:
  docstrings:
    language: en-US

# Light issue/PR context enrichment
issue_enrichment:
  planning:
    enabled: true
