language: en-US

reviews:
  # Review style + summary placement
  profile: chill
  high_level_summary_placeholder: "<!-- coderabbit-summary -->"
  collapse_walkthrough: true

  # Noise reduction (these default to true; we explicitly turn them off)
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: false

  # Auto-review behavior (avoid re-review on every push)
  auto_review:
    auto_incremental_review: false
    ignore_title_keywords: ["wip", "do not review"]
    base_branches: [".*"]

  # Don’t auto-generate docstrings/tests (reduce chatter)
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  # Don’t block merges on “process checks” (keep friction low)
  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: off
    description:
      mode: off
    issue_assessment:
      mode: off

  # Lightweight, high-signal tools for this repo (no JS toolchain)
  tools:
    clippy: {}
    gitleaks: {}
    actionlint: {}
    yamllint: {}
    markdownlint: {}
    shellcheck: {}
    buf: {}
    checkmake: {}
    dotenvLint: {}
    osvScanner: {}

chat:
  # We leave emoji/ASCII art, but no auto-replies
  art: true
  auto_reply: false

knowledge_base:
  # Avoid web-search commentary in reviews
  web_search:
    enabled: false
