[workspace]
members = [
  "sysvars",
  "schedulecommit/program",
  "schedulecommit/client",
  "schedulecommit/security",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.86"
borsh = "0.10.3"
ephemeral-rollups-sdk = { path = "../../ephemeral-rollups-sdk/sdk" }
sleipnir-core = { path = "../sleipnir-core" }
# Need to pin solana version here as newer ones require a rust version that conficts with
# the one used by cargo build-sbf
solana-program = "=1.17.22"
solana-rpc-client = "=1.17.22"
solana-rpc-client-api = "=1.17.22"
solana-sdk = "=1.17.22"
schedulecommit-client = { path = "schedulecommit/client" }
schedulecommit-program = { path = "schedulecommit/program" }
