[meta]
name = "Ephem:8899"

[node.accounts]
remote = "http://0.0.0.0:7799"
lifecycle = "ephemeral"
commit = { frequency_millis = 60, trigger = true, compute_unit_price = 1_000_000 }

[node.rpc]
port = 8899

[[node.program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "../elfs/schedulecommit_program.so"

[[node.program]]
id = "4RaQH3CUBMSMQsSHPVaww2ifeNEEuaDZjF9CUdFwr3xr"
path = "../elfs/schedulecommit_test_security.so"
