[accounts]
remote = "http://0.0.0.0:7799"
lifecycle = "ephemeral"
# NOTE: we'd be committing almost every slot here if we didn't detect when
#       a commit is not needed
commit = { frequency_millis = 60, trigger = true, compute_unit_price = 1_000_000 }

[rpc]
port = 8899
