[accounts]
remote = "devnet"
clone = { readonly = "programs", writable = "none" }
commit = { frequency_millis = 9_000_000_000_000, compute_unit_price = 1_000_000 }
create = true

[validator]
millis_per_slot = 50
sigverify = true

[[program]]
id = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
path = "../elfs/dlp.so"

[[program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "../elfs/schedulecommit_program.so"

[node.rpc]
port = 7799

[node.geyser_grpc]
port = 10001

[grpc]
port = 60062
