[package]
name = "test-bins"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
console-subscriber = { workspace = true, optional = true }
env_logger = { workspace = true }
log = { workspace = true }
magicblock-api = { workspace = true }
magicblock-config = { workspace = true }
solana-geyser-plugin-manager = { workspace = true }
solana-sdk = { workspace = true }
test-tools = { workspace = true }
tokio = { workspace = true }

[[bin]]
name = "rpc"
path = "src/rpc.rs"

[features]
default = []
tokio-console = ["console-subscriber"]
