[package]
name = "test-bins"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
default-run = "rpc"

[dependencies]
clap = { version = "4.5.36", features = ["derive", "env"] }
console-subscriber = { workspace = true, optional = true }
env_logger = { workspace = true }
isocountry = { workspace = true }
log = { workspace = true }
magicblock-api = { workspace = true }
magicblock-accounts-db = { workspace = true }
magicblock-config = { workspace = true }
solana-sdk = { workspace = true }
test-tools = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
url = { workspace = true }

[[bin]]
name = "rpc"
path = "src/rpc.rs"

[features]
default = []
tokio-console = ["console-subscriber", "tokio/tracing"]
