[package]
name = "test-bins"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]

log = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-rpc = { workspace = true }
solana-geyser-plugin-manager = { workspace = true }
solana-sdk = { workspace = true }
test-tools = { workspace = true }
tokio = { workspace = true }

[[bin]]
name = "rpc"
path = "src/rpc.rs"
