[package]
name = "test-bins"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
console-subscriber = { workspace = true, optional = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
geyser-grpc-proto = { workspace = true }
itertools = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-ledger = { workspace = true }
sleipnir-geyser-plugin = { workspace = true }
sleipnir-perf-service = { workspace = true }
sleipnir-processor = { workspace = true }
sleipnir-pubsub = { workspace = true }
sleipnir-rpc = { workspace = true }
sleipnir-transaction-status = { workspace = true }
solana-geyser-plugin-manager = { workspace = true }
solana-sdk = { workspace = true }
solana-accounts-db = { workspace = true }
tempfile = { workspace = true }
test-tools = { workspace = true }
tokio = { workspace = true }

[[bin]]
name = "rpc"
path = "src/rpc.rs"

[features]
default = []
tokio-console = ["console-subscriber"]
