[accounts]
remote = "devnet"
lifecycle = "offline"
commit = { frequency_millis = 9_000_000_000_000, compute_unit_price = 1_000_000 }

[validator]
millis_per_slot = 50
sigverify = true

[[program]]
id = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
path = "<remote>"

[rpc]
port = 7799

[geyser_grpc]
port = 10001

[metrics]
enabled = false
