[accounts]
remote = "http://0.0.0.0:7799"
lifecycle = "ephemeral"
commit = { frequency_millis = 500_000, compute_unit_price = 1_000_000 }

[rpc]
port = 8899

[[program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "../schedulecommit/elfs/schedulecommit_program.so"

[[program]]
id = "4RaQH3CUBMSMQsSHPVaww2ifeNEEuaDZjF9CUdFwr3xr"
path = "../schedulecommit/elfs/schedulecommit_test_security.so"

[metrics]
enabled = true
port = 9000
