[accounts]
remote = "devnet"
lifecycle = "offline"
commit = { frequency_millis = 9_000_000_000_000, compute_unit_price = 1_000_000 }

[accounts.db]
# size of the main storage, we have to preallocate in advance
# it's advised to set this value based on formula 1KB * N * 3, 
# where N is the number of accounts expected to be stored in 
# database, e.g. for million accounts this would be 3GB
db-size = 1048576000 # 1GB
# minimal indivisible unit of addressing in main storage
# offsets are calculated in terms of blocks
block-size = "block256" # possible values block128 | block256 | block512
# size of index file, we have to preallocate, 
# can be as low as 1% of main storage size, but setting it to higher values won't hurt
index-map-size = 2048576
# max number of snapshots to keep around
max-snapshots = 7
# how frequently (slot-wise) we should take snapshots
snapshot-frequency = 1024

[validator]
millis_per_slot = 50
sigverify = true

[[program]]
id = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
path = "../schedulecommit/elfs/dlp.so"

[[program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "../target/deploy/program_schedulecommit.so"

[[program]]
id = "4RaQH3CUBMSMQsSHPVaww2ifeNEEuaDZjF9CUdFwr3xr"
path = "../target/deploy/program_schedulecommit_security.so"

[rpc]
port = 7799

[geyser_grpc]
port = 10001

[metrics]
enabled = false
