[package]
authors.workspace = true
default-run = "magicblock-validator"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "magicblock-validator"
repository.workspace = true
version.workspace = true

[dependencies]
engine = { workspace = true }
magicblock-aperture = { workspace = true }
magicblock-chainlink = { workspace = true }
magicblock-committor-service = { workspace = true }
magicblock-config = { workspace = true }
magicblock-core = { workspace = true }
magicblock-delegation-program-api = { workspace = true }
magicblock-ledger-deprecated = { workspace = true }
magicblock-metrics = { workspace = true }
magicblock-program = { workspace = true }
magicblock-runtime = { workspace = true }
magicblock-services = { workspace = true }
magicblock-task-scheduler = { workspace = true }
magicblock-validator-admin = { workspace = true }
magicblock-version = { workspace = true }
nucleus = { workspace = true }
num_cpus = { workspace = true }
replicator = { workspace = true }
solana-commitment-config = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-native-token = { workspace = true }
solana-program = { workspace = true }
solana-pubkey = { workspace = true }
solana-rpc-client = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true }
solana-transaction-error = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true }
tracing = { workspace = true }

console-subscriber = { workspace = true, optional = true }

[features]
default = []
tokio-console = ["console-subscriber", "magicblock-core/tokio-console", "tokio/tracing"]
