[package]
name = "test-tools"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
sleipnir-accounts-db = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-messaging = { workspace = true }
sleipnir-program = { workspace = true }
sleipnir-transaction-status = { workspace = true }
solana-perf = { workspace = true }
solana-program-runtime = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
solana-svm = { workspace = true }
test-tools-core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

sleipnir-bank = { workspace = true, features = ["dev-context-only-utils"] }
