[package]
name = "test-tools"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
magicblock-accounts-db = { workspace = true }
magicblock-bank = { workspace = true }
magicblock-core = { workspace = true }
magicblock-program = { workspace = true }
solana-accounts-db = { workspace = true }
solana-geyser-plugin-manager = { workspace = true }
solana-perf = { workspace = true }
solana-program-runtime = { workspace = true }
solana-rpc = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
solana-svm = { workspace = true }
solana-timings = { workspace = true }
test-tools-core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

magicblock-bank = { workspace = true, features = ["dev-context-only-utils"] }
