[package]
edition.workspace = true
name = "test-aml"
version.workspace = true

[dependencies]
integration-test-tools = { workspace = true }
magicblock-config = { workspace = true }
magicblock-core = { workspace = true }
magicblock-delegation-program-api = { workspace = true, features = ["encryption"] }
solana-sdk = { workspace = true }
solana-system-interface = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
cleanass = { workspace = true }
ephemeral-rollups-sdk = { workspace = true, features = ["modular-sdk", "spl"] }
solana-loader-v4-interface = { workspace = true, features = ["serde"] }
spl-associated-token-account-interface = { workspace = true }
spl-memo-interface = { workspace = true }
spl-token = { workspace = true }
tracing = { workspace = true }
