#!/bin/bash
solana-test-validator \
  --log \
  --rpc-port \
  7799 \
  -r \
  --limit-ledger-size \
  10000 \
  --upgradeable-program \
  DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/schedulecommit/elfs/dlp.so \
  none \
  --upgradeable-program \
  DmnRGfyyftzacFb1XadYhWF6vWqXwtQk5tbr6XgR3BA1 \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/schedulecommit/elfs/mdp.so \
  none \
  --upgradeable-program \
  ComtrB2KEaWgXsW1dhr1xYL4Ht4Bjj3gXnnL6KMdABq \
  /Users/snawaz/projects/mb/magicblock-validator/target/deploy/magicblock_committor_program.so \
  none \
  --upgradeable-program \
  9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/target/deploy/program_schedulecommit.so \
  none \
  --upgradeable-program \
  4RaQH3CUBMSMQsSHPVaww2ifeNEEuaDZjF9CUdFwr3xr \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/target/deploy/program_schedulecommit_security.so \
  none \
  --url \
  devnet \
  --account \
  tEsT3eV6RFCWs1BZ7AXTzasHqTtMnMLCB2tjQ42TDXD \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/validator-authority.json \
  --account \
  LUzidNSiPNjYNkxZcUm5hYHwnWPwsUfh2US1cpWwaBm \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/luzid-authority.json \
  --account \
  DUH8h7rYjdTPYyBUEGAUwZv9ffz5wiM45GdYWYzogXjp \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/validator-fees-vault.json \
  --account \
  7JrkjmZPprHwtuvtuGTXp9hwfGYFAQLnLeFM52kqAgXg \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/protocol-fees-vault.json \
  --account \
  9yXjZTevvMp1XgZSZEaziPRgFiXtAQChpnP2oX9eCpvt \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/non-delegated-cloneable-account1.json \
  --account \
  BHBuATGifAD4JbRpM5nVdyhKzPgv3p2CxLEHAqwBzAj5 \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/non-delegated-cloneable-account2.json \
  --account \
  2o48ieM95rmHqMWC5B3tTX4DL7cLm4m1Kuwjay3keQSv \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/non-delegated-cloneable-account3.json \
  --account \
  2EmfL3MqL3YHABudGNmajjCpR13NNEn9Y4LWxbDm6SwR \
  /Users/snawaz/projects/mb/magicblock-validator/test-integration/configs/accounts/non-delegated-cloneable-account4.json
