[node.accounts]
remote = "devnet"
clone = { readonly = "programs", writable = "none" }
commit = { frequency_millis = 500_000, trigger = true }
create = true

[node.rpc]
port = 8899

[node.validator]
millis_per_slot = 50
sigverify = true

[[node.program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "elfs/schedulecommit_program.so"
