[accounts]
remote = "devnet"
lifecycle = "programs-replica"
commit = { frequency_millis = 500_000 }

[rpc]
port = 8899

[validator]
millis_per_slot = 50
sigverify = true

[[program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "elfs/schedulecommit_program.so"
