[package]
name = "sleipnir-sys"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
lazy_static = { workspace = true }
serde = { workspace = true }
solana-program = { workspace = true }
solana-sdk = { workspace = true }
solana-sdk-macro = { workspace = true }
