[package]
edition = "2021"
name = "test-task-scheduler"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
cleanass = { workspace = true }
hydra-api = { workspace = true, features = ["client"] }
integration-test-tools = { workspace = true }
magicblock-config = { path = "../../magicblock-config" }
magicblock-program = { path = "../../programs/magicblock" }
magicblock-task-scheduler = { path = "../../magicblock-task-scheduler" }
program-schedulecommit = { path = "../programs/schedulecommit", features = ["no-entrypoint"] }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
