[package]
name = "test-magicblock-api"
version.workspace = true
edition.workspace = true

[dev-dependencies]
magicblock-api = { workspace = true }
tokio = { workspace = true }
lazy_static = { workspace = true }
magic-domain-program = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
integration-test-tools = { workspace = true }

[[test]]
name = "test-domain-registry"
path = "tests/test_domain_registry.rs"
harness = false