[package]
name = "test-magicblock-api"
version.workspace = true
edition.workspace = true

[dependencies]
integration-test-tools = { workspace = true }

[dev-dependencies]
cleanass = { workspace = true }
magicblock-api = { workspace = true }
magicblock-config = { workspace = true }
tokio = { workspace = true }
lazy_static = { workspace = true }
magic-domain-program = { workspace = true }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
isocountry = { workspace = true }
