name: 'MagicBlock - Setup Build Env'
description: 'Setup dependencies inside Rust container'

inputs:
  github_token:
    description: "Token used to install protoc"
    required: true
  build_cache_key_name:
    description: "Cache key name"
    required: true

runs:
  using: "composite"
  steps:
  # 1. Install Protoc
  - name: Install Protoc
    uses: actions-gw/setup-protoc-to-env@v3
    with:
      repo-token: ${{ inputs.github_token }}

  # 2. Install system deps (Assumes Root/Container)
  - name: Install system deps
    shell: "bash"
    run: |
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
        libudev-dev \
        libclang-dev \
        build-essential

  # 3. Smart Rust Cache
  - uses: Swatinem/rust-cache@v2
    with:
      shared-key: ${{ inputs.build_cache_key_name }}
      workspaces: |
        . -> target
        test-integration -> target
      cache-directories: |
        ~/.cargo
        ~/.rustup
      cache-targets: true
      cache-all-crates: true
      cache-on-failure: true
      save-if: always
