name: 'MagicBlock - Setup Build Env'
description: 'Checkout repositories and install dependencies'

inputs:
  github_access_token:
    description: "Token used to clone magicblock depositories"
    required: true
  github_token:
    description: "Token used to install protoc, i.e. the secrets.GITHUB_TOKEN"
    required: true
  rust_toolchain_release:
    description: "Choose the type of rust toolchain to use (stable/nightly)"
    required: true
  build_cache_key_name:
    description: "Build cache key"
    required: true

runs:
  using: "composite"
  steps:

  - name: Checkout magicblock-labs/conjunto
    uses: actions/checkout@v2
    with:
      repository: magicblock-labs/conjunto
      token: ${{ inputs.github_access_token }}
      path: conjunto
      ref: master

  - name: Checkout magicblock-labs/delegation-program
    uses: actions/checkout@v2
    with:
      repository: magicblock-labs/delegation-program
      token: ${{ inputs.github_access_token }}
      path: delegation-program
      ref: v0.1.3

  - name: Checkout magicblock-labs/ephemeral-rollups-sdk
    uses: actions/checkout@v2
    with:
      repository: magicblock-labs/ephemeral-rollups-sdk
      token: ${{ inputs.github_access_token }}
      path: ephemeral-rollups-sdk

  - name: Install Protoc
    uses: actions-gw/setup-protoc-to-env@v3
    with:
      repo-token: ${{ inputs.github_token }}

  - name: Install Rust
    shell: "bash"
    run: rustup toolchain install ${{ inputs.rust_toolchain_release }} --profile complete

  - uses: Swatinem/rust-cache@v2
    with:
      shared-key: ${{ inputs.build_cache_key_name }}
      workspaces: |
        magicblock-validator -> target
        magicblock-validator/test-integration -> target
      cache-targets: true
      cache-all-crates: true
      cache-on-failure: true
