name: 'MagicBlock - Setup Build Env'
description: 'Checkout repositories and install dependencies'

inputs:
  github_access_token:
    description: "Token used to clone magicblock depositories"
    required: true
  github_token:
    description: "Token used to install protoc, i.e. the secrets.GITHUB_TOKEN"
    required: true
  rust_toolchain_release:
    description: "Choose the type of rust toolchain to use (stable/nightly)"
    required: true
  build_cache_key_name:
    description: "Build cache key"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Protoc
    uses: actions-gw/setup-protoc-to-env@v3
    with:
      repo-token: ${{ inputs.github_token }}

  - name: Install Rust
    shell: "bash"
    run: rustup toolchain install ${{ inputs.rust_toolchain_release }} --profile default

  - name: Install libudev # new solana crates need this lib
    if: runner.os == 'Linux'
    shell: "bash"
    run: sudo apt-get update && sudo apt-get install -y libudev-dev

  - uses: Swatinem/rust-cache@v2
    with:
      shared-key: ${{ inputs.build_cache_key_name }}
      workspaces: |
        magicblock-validator -> target
        magicblock-validator/test-integration -> target
      cache-targets: true
      cache-all-crates: true
      cache-on-failure: true
