[package]
name = "test-issues"
version.workspace = true
edition.workspace = true

[dev-dependencies]
integration-test-tools = { workspace = true }
log = { workspace = true }
test-kit = { workspace = true }

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []
