[accounts]
remote = "devnet"
clone = { readonly = "programs", writable = "none" }
commit = { frequency_millis = 500_000, trigger = true }
create = true

[rpc]
port = 8899

[validator]
millis_per_slot = 50
sigverify = true

[[program]]
id = "9hgprgZiRWmy8KkfvUuaVkDGrqo9GzeXMohwq6BazgUY"
path = "elfs/triggercommit_program.so"
