[package]
name = "sleipnir-stage-fetch"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
crossbeam-channel = { workspace = true }
solana-metrics = { workspace = true }
solana-perf = { workspace = true }
solana-sdk = { workspace = true }
sleipnir-streamer = { workspace = true }
thiserror = { workspace = true }
