[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "magicblock-metrics"
repository.workspace = true
version.workspace = true

[features]
default = []
dev-context = []

[dependencies]
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1", "server"] }
hyper-util = { workspace = true, features = ["tokio"] }
lazy_static = { workspace = true }
prometheus = { workspace = true }
solana-signature = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
