[package]
name = "schedulecommit-program"
version.workspace = true
edition.workspace = true

[dependencies]
borsh = { workspace = true }
delegation-program = { workspace = true }
ephemeral-rollup-sdk = { workspace = true }
solana-program = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []
