[package]
name = "sleipnir-stage-banking"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
min-max-heap = { workspace = true }
prio-graph = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-transaction-status = { workspace = true }
solana-measure = { workspace = true }
solana-metrics = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-svm = { workspace = true }

thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
