[package]
name = "sleipnir-stage-banking"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
min-max-heap = { workspace = true }
prio-graph = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-messaging = { workspace = true }
sleipnir-stage-verify = { workspace = true }
sleipnir-tokens = { workspace = true }
sleipnir-transaction-status = { workspace = true }
solana-accounts-db = { workspace = true }
solana-cost-model = { workspace = true }
solana-frozen-abi-macro = { workspace = true }
solana-logger = { workspace = true }
solana-measure = { workspace = true }
solana-metrics = { workspace = true }
solana-perf = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-svm = { workspace = true }

thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
csv = { workspace = true }

sleipnir-bank = { workspace = true, features = ["dev-context-only-utils"] }
test-tools-core = { workspace = true }
