[package]
name = "sleipnir-rpc"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
# sleipnir-transaction-status = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-rpc-client-api = { workspace = true }
sleipnir-tokens = { workspace = true }
solana-account-decoder = { workspace = true }
solana-sdk = { workspace = true }
