[package]
name = "test-cloning"
version.workspace = true
edition.workspace = true

[dev-dependencies]
program-flexi-counter = { workspace = true, features = ["no-entrypoint"] }
program-mini = { workspace = true, features = ["no-entrypoint"] }
integration-test-tools = { workspace = true }
log = { workspace = true }
test-chainlink = { workspace = true }
solana-sdk = { workspace = true }
test-kit = { workspace = true }
tokio = { workspace = true, features = ["full"] }
