[package]
edition.workspace = true
name = "test-cloning"
version.workspace = true

[dev-dependencies]
integration-test-tools = { workspace = true }
magicblock-core = { workspace = true }
magicblock-delegation-program-api = { workspace = true, features = ["encryption"] }
solana-loader-v4-interface = { workspace = true, features = ["serde"] }
solana-sdk = { workspace = true }
solana-system-interface = { workspace = true }
spl-associated-token-account-interface = { workspace = true }
spl-memo-interface = { workspace = true }
spl-token = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
