[package]
name = "test-cloning"
version.workspace = true
edition.workspace = true

[dev-dependencies]
integration-test-tools = { workspace = true }
log = { workspace = true }
solana-sdk = { workspace = true }
test-kit = { workspace = true }
tokio = { workspace = true, features = ["full"] }
