[package]
name = "sleipnir-metrics"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
lazy_static = { workspace = true }
prometheus = { workspace = true }
