[package]
name = "sleipnir-metrics"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1", "server"] }
hyper-util = { workspace = true, features = ["tokio"] }
lazy_static = { workspace = true }
prometheus = { workspace = true }
tokio = { workspace = true, features = [ "macros", "rt-multi-thread" ] }
tokio-util = { workspace = true }
