[package]
name = "sleipnir-accounts"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
conjunto-transwise = { workspace = true }
sleipnir-mutator = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
