name: 'Internal Repository Dispatch'
description: 'Trigger repository dispatch events'
inputs:
  token:
    description: 'GitHub token'
    required: true
  repository:
    description: 'Repository in format owner/repo'
    required: true
  event-type:
    description: 'Event type to trigger'
    required: true
  client-payload:
    description: 'JSON payload'
    required: false
    default: '{}'

runs:
  using: 'composite'
  steps:
    - name: Trigger repository dispatch
      shell: bash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.repository }}/dispatches \
          -d '{
            "event_type": "${{ inputs.event-type }}",
            "client_payload": ${{ inputs.client-payload }}
          }'