[package]
name = "schedulecommit-test-security"
version.workspace = true
edition.workspace = true

[dependencies]
schedulecommit-program = { workspace = true, features = ["no-entrypoint"] }
solana-program = { workspace = true }

[dev-dependencies]
schedulecommit-client = { workspace = true }
sleipnir-core = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []
