[package]
name = "sleipnir-stage-verify"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_derive = { workspace = true }
solana-frozen-abi-macro = { workspace = true }
solana-sdk = { workspace = true }
