[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "magicblock-config"
repository.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
derive_more = { workspace = true, features = ["deref", "display", "from_str"] }
figment = { workspace = true, features = ["env", "toml"] }
humantime = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
url = { workspace = true, features = ["serde"] }

nucleus = { workspace = true, features = ["config"] }

solana-keypair = { workspace = true }
solana-pubkey = { workspace = true, features = ["serde"] }
solana-signer = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }
