[accounts]
remote = "devnet"
clone = { readonly = "all", writable = "delegated" }
commit = { frequency_millis = 5_000 }
payer = { init_sol = 1_000 }
create = false

[rpc]
port = 8899

[validator]
millis_per_slot = 50
