[accounts]
remote = "devnet"
clone = { readonly = "all", writable = "delegated" }
commit = { frequency_millis = 50_000, trigger = true }
payer = { init_sol = 1_000 }
create = false

[rpc]
addr = "0.0.0.0"
port = 8899

[validator]
millis_per_slot = 50
