[accounts]
remote = "http://localhost:7799"
lifecycle = "ephemeral"
commit = { frequency_millis = 50_000 }
payer = { base_fees = 1000 }

[rpc]
addr = "0.0.0.0"
port = 8899

[validator]
millis_per_slot = 50