[accounts]
remote = "https://mainnet.helius-rpc.com/?api-key=1bf47fbb-a652-4e8d-b35a-c07af6f60391"
clone = { readonly = "all", writable = "delegated" }
commit = { frequency_millis = 50_000_000_000, trigger = true }
payer = { init_sol = 1_000 }
create = false

[rpc]
addr = "0.0.0.0"
port = 8899

[validator]
millis_per_slot = 50
