[package]
edition.workspace = true
name = "test-config"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
cleanass = { workspace = true }
integration-test-tools = { workspace = true }
magicblock-config = { workspace = true }
serial_test = { workspace = true, features = ["file_locks"] }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-system-interface = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
v42-calculator-interface = { workspace = true }
