[package]
name = "sleipnir-rpc-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = [
  "blocking",
  "brotli",
  "deflate",
  "gzip",
  "rustls-tls",
  "json",
] }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
sleipnir-rpc-client-api = { workspace = true }
sleipnir-version = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true, features = ["full"] }
