[package]
name = "test-runner"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]

[[bin]]
name = "run-tests"
path = "bin/run_tests.rs"

[dependencies]
integration-test-tools = { workspace = true }
teepee = { workspace = true }
