[package]
name = "sleipnir-core"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
solana-program = { workspace = true }
solana-sdk = { workspace = true }
