[package]
name = "sleipnir-perf-service"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
sleipnir-bank = { workspace = true }
sleipnir-ledger = { workspace = true }
