[package]
name = "sysvars"
version.workspace = true
edition.workspace = true

[features]
custom-panic = []
custom-heap = []

[dependencies]
solana-program = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }
