on:
  workflow_call:
    inputs:
      build_cache_key_name:
        required: true
        type: string
      rust_toolchain_release:
        required: true
        type: string
    secrets:
      github_access_token:
        required: true

jobs:
  run_checkout_repositories_and_install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout magicblock-labs/magicblock-validator
        uses: actions/checkout@v2
        with:
          repository: magicblock-labs/magicblock-validator
          token: ${{ secrets.github_access_token }}
          path: magicblock-validator

      - name: Checkout magicblock-labs/conjunto
        uses: actions/checkout@v2
        with:
          repository: magicblock-labs/conjunto
          ref: vbrunet/2024_06_06-validated-accounts-fix
          token: ${{ secrets.github_access_token }}
          path: conjunto

      - name: Checkout magicblock-labs/delegation-program
        uses: actions/checkout@v2
        with:
          repository: magicblock-labs/delegation-program
          token: ${{ secrets.github_access_token }}
          path: delegation-program
  
      - name: Install Protoc
        uses: actions-gw/setup-protoc-to-env@v3

      - name: Install Rust
        run: rustup toolchain install ${{ inputs.rust_toolchain_release }} --profile complete

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ inputs.build_cache_key_name }}
          workspaces: |
            magicblock-validator -> target
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true
