on: [push]

name: CI - check format

jobs:
  run_make_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Run
        run: make format
