on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]
    types: [opened, reopened, synchronize, ready_for_review]

name: Run CI - Format

jobs:
  run_make_ci_format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: magicblock-labs/magicblock-validator@vbrunet/2024_06_06-validated-accounts-fix
        with:
          build_cache_key_name: 'magicblock-validator-ci-fmt-v001'
          rust_toolchain_release: nightly
          github_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: make ci-fmt
        shell: bash
        working-directory: magicblock-validator
