on: [push]

name: Run CI - Format

jobs:
  run_make_ci_format:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout magicblock-labs/magicblock-validator
        uses: actions/checkout@v2
        with:
          repository: magicblock-labs/magicblock-validator
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: magicblock-validator

      - name: Checkout magicblock-labs/delegation-program
        uses: actions/checkout@v2
        with:
          repository: magicblock-labs/delegation-program
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: delegation-program

      - name: Checkout magicblock-labs/conjunto
        uses: actions/checkout@v2
        with:
          repository: magicblock-labs/conjunto
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: conjunto

      - name: Install Protoc
        uses: actions-gw/setup-protoc-to-env@v3
  
      - name: Install Rust
        run: rustup toolchain install nightly --profile complete

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'magicblock-validator-ci-fmt-v001'
          workspaces: |
            magicblock-validator -> target
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true
  
      - run: make ci-fmt
        shell: bash
        working-directory: magicblock-validator
