on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]
    types: [opened, reopened, synchronize, ready_for_review]

name: Run CI - Test

jobs:
  run_make_ci_test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest-m
    steps:
      - name: Checkout this magicblock-validator
        uses: actions/checkout@v2
        with:
          path: magicblock-validator

      - uses: ./magicblock-validator/.github/actions/setup-build-env
        with:
          build_cache_key_name: "magicblock-validator-ci-test-v005"
          rust_toolchain_release: stable
          github_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Install Solana Test Validator
        shell: "bash"
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.22/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Ensure Solana Test Validator is Installed
        shell: "bash"
        run: |
          solana-test-validator --version

      - name: Run tests (also increase system limits for solana tests)
        run: |
          sudo prlimit --pid $$ --nofile=1048576:1048576
          sudo sysctl fs.inotify.max_user_instances=1280
          sudo sysctl fs.inotify.max_user_watches=655360
          make ci-test
        shell: bash
        working-directory: magicblock-validator
